config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "note#index"

  get 'note/:id' => "note#show", as: :note

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/note_controller.rb
class NoteController < ApplicationController
  before_action :authenticate_user!

  def index
    @notes = Note.all
  end

  def show
    @note = Note.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lipsum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/note/index.html.erb
<h1>Notes</h1>

<ul class="notes-list">
    <% @notes.each do |note| %>
<li>

    <%= link_to note.name, note_path(note.id)  %>
</li>

    <% end %>
</ul>

app/views/note/show.html.erb
<h1><%= @note.name %></h1>
<p><%= @note.body %></p>